version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: /Dockerfile
    command: bash -c "service cron start && apache2-foreground"
    container_name: php_83_app
    volumes:
      - .:/var/www
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      XDEBUG_MODE: debug
    ports:
      - "8000:80"
      - "9003:9003"
    depends_on:
      db :
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: garden
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./flyway/sql:/flyway/sql
    command: -url=jdbc:mysql://db:3306/garden?allowPublicKeyRetrieval=true -user=user -password=secret migrate

volumes:
  db_data:
